# -*- coding: utf-8 -*-
"""
/***************************************************************************
 AerialPhotographyGUI
                                 A QGIS plugin
 Plugin for aerial photography
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-07-29
        copyright            : (C) 2024 by Violet
        email                : madarich18@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load AerialPhotographyGUI class from file AerialPhotographyGUI.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .Aerial_Photography_GUI import AerialPhotographyGUI
    return AerialPhotographyGUI(iface)
